version: '3.7'

services:
  api:
    build: .
    command: "symfony server:start --no-tls"
    user: 1000:1000
    volumes:
      - ./:/code
    ports:
      - 8000:8000

  consumer:
    build: .
    command: "symfony messenger:consume async"
    user: 1000:1000
    volumes:
      - ./:/code

  management:
    image: rabbitmq:management
    ports:
      - 8080:15672

  rabbit:
    image: rabbitmq
